### ISSUE TITLE
Webpage Flows

### ISSUE THREAD

**Issue by charlottello** [codefordenver/di_geocoding#18]
Create flow that will show how each page will interact with the others

**Comment by nguyent85** [comment]
![website flow chart-01](https://cloud.githubusercontent.com/assets/19574783/17633781/549269a8-608c-11e6-8b86-cd35e87831b2.jpg)

**Comment by charlottello** [comment]
Great job!  Thank you

**Comment by KeynesYouDigIt** [comment]
beautiful, this actually helps us on the back
